// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package fptframework.outhouse.security;

@net.sf.jni4net.attributes.ClrType
public class LibEncryption extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected LibEncryption(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public LibEncryption() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        fptframework.outhouse.security.LibEncryption.__ctorLibEncryption0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorLibEncryption0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)LSystem/String;")
    public native static java.lang.String Encrypt_Password(java.lang.String PasswordData);
    
    public static system.Type typeof() {
        return fptframework.outhouse.security.LibEncryption.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        fptframework.outhouse.security.LibEncryption.staticType = staticType;
    }
    //</generated-proxy>
}
